import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1787473282104 implements MigrationInterface {
    name = 'InitSchema1787473282104'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('user', 'owner', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum" AS ENUM('active', 'banned', 'pending')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "phone" character varying, "password_hash" character varying NOT NULL, "role" "public"."user_role_enum" NOT NULL DEFAULT 'user', "status" "public"."user_status_enum" NOT NULL DEFAULT 'pending', "lat" numeric(10,7), "lng" numeric(10,7), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f169d18dc7fce81f4c20974fd0" ON "users" ("phone") WHERE phone IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."skill_level_enum" AS ENUM('beginner', 'intermediate', 'advanced')`);
        await queryRunner.query(`CREATE TABLE "user_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "full_name" character varying, "avatar_url" character varying, "bio" text, "skill_level" "public"."skill_level_enum", "birthday" date, "gender" character varying, CONSTRAINT "UQ_6ca9503d77ae39b4b5a6cc3ba88" UNIQUE ("user_id"), CONSTRAINT "PK_1ec6662219f4605723f1e41b6cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6ca9503d77ae39b4b5a6cc3ba8" ON "user_profiles" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "owner_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "business_name" character varying, "business_license" character varying, "bank_account" character varying, "verified_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_f9da160266a21b0f39b6aeaca7a" UNIQUE ("user_id"), CONSTRAINT "PK_f50964d90a34725685860cbdda5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f9da160266a21b0f39b6aeaca7" ON "owner_profiles" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."field_status_enum" AS ENUM('pending', 'active', 'hidden', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."deposit_type_enum" AS ENUM('percentage', 'fixed_amount')`);
        await queryRunner.query(`CREATE TABLE "fields" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_id" uuid NOT NULL, "name" character varying NOT NULL, "address" character varying NOT NULL, "district" character varying NOT NULL, "lat" numeric(10,7), "lng" numeric(10,7), "description" text, "status" "public"."field_status_enum" NOT NULL DEFAULT 'pending', "require_deposit" boolean NOT NULL DEFAULT false, "deposit_type" "public"."deposit_type_enum", "deposit_value" numeric(14,2), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ee7a215c6cd77a59e2cb3b59d41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fd7b6f73d3dbe8cb0cc5cd510c" ON "fields" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb540818c27426841e06b36b09" ON "fields" ("district") `);
        await queryRunner.query(`CREATE TYPE "public"."court_status_enum" AS ENUM('active', 'maintenance', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "field_courts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "field_id" uuid NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "status" "public"."court_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_6be33cd911868d7f7c578cbc93c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb774c35a4f3285bf483e801e5" ON "field_courts" ("field_id") `);
        await queryRunner.query(`CREATE TABLE "field_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "field_id" uuid NOT NULL, "url" character varying NOT NULL, "is_thumbnail" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_fcdca2406605c29b9f9ead003af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_756ccc25e9484dcf6453f90947" ON "field_images" ("field_id") `);
        await queryRunner.query(`CREATE TABLE "field_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "field_id" uuid NOT NULL, "name" character varying NOT NULL, "price" numeric(14,2) NOT NULL DEFAULT '0', "unit" character varying, CONSTRAINT "PK_17576d37a7a87eded4dd6eb36ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb1beabceee095ac2e8ed72c25" ON "field_services" ("field_id") `);
        await queryRunner.query(`CREATE TYPE "public"."day_type_enum" AS ENUM('weekday', 'weekend')`);
        await queryRunner.query(`CREATE TABLE "field_pricing" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "field_id" uuid NOT NULL, "day_type" "public"."day_type_enum" NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "price" numeric(14,2) NOT NULL, CONSTRAINT "PK_921bd4d902b3804419d92c99806" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3766133563eefed9888347effa" ON "field_pricing" ("field_id") `);
        await queryRunner.query(`CREATE TYPE "public"."booking_status_enum" AS ENUM('pending', 'confirmed', 'rejected', 'cancelled', 'completed')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_enum" AS ENUM('cash', 'deposit_online')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum" AS ENUM('not_required', 'pending', 'paid', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "field_id" uuid NOT NULL, "field_court_id" uuid, "booking_date" date NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "status" "public"."booking_status_enum" NOT NULL DEFAULT 'pending', "total_price" numeric(14,2) NOT NULL, "payment_method" "public"."payment_method_enum" NOT NULL, "payment_status" "public"."payment_status_enum" NOT NULL DEFAULT 'not_required', "deposit_amount" numeric(14,2) NOT NULL DEFAULT '0', "owner_note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_64cd97487c5c42806458ab5520" ON "bookings" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f80ee3c0f6b2adf57520dc9e97" ON "bookings" ("field_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_88c0e04c7c95a23d0049ba05fc" ON "bookings" ("field_court_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b406d71d65b8e16c5cf6e9b3ba" ON "bookings" ("field_id", "booking_date", "start_time", "end_time") `);
        await queryRunner.query(`CREATE TABLE "booking_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "service_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "price_snapshot" numeric(14,2) NOT NULL, CONSTRAINT "UQ_12f15721492a512bc6165c44426" UNIQUE ("booking_id", "service_id"), CONSTRAINT "PK_8997bf4d0728c8740c87694d59a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_813fb23d7e327b6d9cff929cce" ON "booking_services" ("booking_id") `);
        await queryRunner.query(`CREATE TYPE "public"."post_skill_level_enum" AS ENUM('beginner', 'intermediate', 'advanced')`);
        await queryRunner.query(`CREATE TYPE "public"."post_status_enum" AS ENUM('open', 'matched', 'closed')`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying NOT NULL, "content" text, "lat" numeric(10,7) NOT NULL, "lng" numeric(10,7) NOT NULL, "play_date" date NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "skill_level_required" "public"."post_skill_level_enum", "status" "public"."post_status_enum" NOT NULL DEFAULT 'open', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4f9a7bd77b489e711277ee598" ON "posts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7374a48c04249418e45384b643" ON "posts" ("play_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d6a751a1943909d10bcc5a140" ON "posts" ("lat", "lng") `);
        await queryRunner.query(`CREATE TABLE "post_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "user_id" uuid NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2e99e04b4a1b31de6f833c18ced" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e8ffd07822f03f90f637b13cd5" ON "post_comments" ("post_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8eb985b7bd35fd7bc760b6cbe8" ON "post_comments" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."match_status_enum" AS ENUM('pending', 'accepted', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "post_matches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "applicant_id" uuid NOT NULL, "status" "public"."match_status_enum" NOT NULL DEFAULT 'pending', "conversation_id" uuid, CONSTRAINT "UQ_8f1d0e162496ea24d21619cce15" UNIQUE ("post_id", "applicant_id"), CONSTRAINT "PK_618fcb78a7b75232326c1b52138" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_547a10a97b30830634e4917ee8" ON "post_matches" ("post_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_427e1e52f6accefda55ac33020" ON "post_matches" ("applicant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."conversation_type_enum" AS ENUM('direct')`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."conversation_type_enum" NOT NULL DEFAULT 'direct', "related_post_id" uuid, "related_field_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_by_sender" TIMESTAMP WITH TIME ZONE, "deleted_by_receiver" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_19bb13367263f4abb451b75838" ON "conversations" ("related_post_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d863718b78a19a4259f34dcae2" ON "conversations" ("related_field_id") `);
        await queryRunner.query(`CREATE TABLE "conversation_members" ("conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5fa9076068b6f2a26fb793d2439" PRIMARY KEY ("conversation_id", "user_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."message_type_enum" AS ENUM('text', 'image')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "content" text NOT NULL, "message_type" "public"."message_type_enum" NOT NULL DEFAULT 'text', "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22133395bd13b970ccd0c34ab2" ON "messages" ("sender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8584a1974e1ca95f4861d975ff" ON "messages" ("conversation_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "price" numeric(14,2) NOT NULL, "duration_days" integer NOT NULL, "benefit" jsonb NOT NULL DEFAULT '{}'::jsonb, CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_status_enum" AS ENUM('active', 'expired', 'pending_payment')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "status" "public"."subscription_status_enum" NOT NULL DEFAULT 'pending_payment', "start_date" date, "end_date" date, CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39a0b4bd3117b9d4c9cd696fee" ON "subscriptions" ("owner_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."transaction_type_enum" AS ENUM('subscription', 'booking_deposit')`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_status_enum" AS ENUM('pending', 'success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."transaction_type_enum" NOT NULL, "ref_id" uuid, "amount" numeric(14,2) NOT NULL, "status" "public"."transaction_status_enum" NOT NULL DEFAULT 'pending', "gateway" character varying, "gateway_ref" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9acc6efa76de013e8c1553ed2" ON "transactions" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e64933661819e67db6986232c6" ON "transactions" ("gateway_ref") WHERE gateway_ref IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_4ca327ebb6c902e8bad5932105" ON "transactions" ("type", "ref_id") `);
        await queryRunner.query(`CREATE TABLE "field_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "field_id" uuid NOT NULL, "reviewer_id" uuid NOT NULL, "booking_id" uuid NOT NULL, "rating" integer NOT NULL, "is_flagged" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_db2937370fd888c5de440aab609" UNIQUE ("booking_id"), CONSTRAINT "CHK_field_reviews_rating" CHECK (rating >= 1 AND rating <= 5), CONSTRAINT "PK_9c84a27be944ba0c3bc9a9bcff3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0401bfc63155e3d2e154631c85" ON "field_reviews" ("field_id") `);
        await queryRunner.query(`CREATE TABLE "user_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "target_user_id" uuid NOT NULL, "reviewer_id" uuid NOT NULL, "post_id" uuid NOT NULL, "rating" integer NOT NULL, "is_flagged" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_464b3c7305c93fb5c2625771035" UNIQUE ("target_user_id", "reviewer_id", "post_id"), CONSTRAINT "CHK_user_reviews_rating" CHECK (rating >= 1 AND rating <= 5), CONSTRAINT "PK_24de027fbe1bf4d1c39817dc8da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2a15dfcd7aa8b8f61431364d19" ON "user_reviews" ("target_user_id") `);
        await queryRunner.query(`CREATE TABLE "field_rating_summary" ("field_id" uuid NOT NULL, "avg_rating" numeric(3,2) NOT NULL DEFAULT '0', "total_reviews" integer NOT NULL DEFAULT '0', "bayesian_score" numeric(8,4) NOT NULL DEFAULT '0', "district" character varying NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fc01b20ef049ed9b50510f488f0" PRIMARY KEY ("field_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4397e1893c028b96e04f208f76" ON "field_rating_summary" ("bayesian_score") `);
        await queryRunner.query(`CREATE INDEX "IDX_88452e999eb3af6a696a21dafe" ON "field_rating_summary" ("district") `);
        await queryRunner.query(`CREATE TABLE "user_rating_summary" ("user_id" uuid NOT NULL, "avg_rating" numeric(3,2) NOT NULL DEFAULT '0', "total_reviews" integer NOT NULL DEFAULT '0', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_592b84a02c86f8e371f374c93e4" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum" AS ENUM('booking_confirmed', 'booking_rejected', 'subscription_expiring', 'new_message')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."notification_type_enum" NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "ref_id" uuid, "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0f57a0c3adbbfd460935b7b046" ON "notifications" ("user_id", "is_read", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."approval_type_enum" AS ENUM('owner_register', 'field_create', 'field_update')`);
        await queryRunner.query(`CREATE TYPE "public"."approval_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "approval_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."approval_type_enum" NOT NULL, "target_id" uuid, "requested_by" uuid NOT NULL, "status" "public"."approval_status_enum" NOT NULL DEFAULT 'pending', "reviewed_by" uuid, "note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_484806bb8ff331b851fc75973c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0bcfff2aed6c93f6fa089720b3" ON "approval_requests" ("requested_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_802fa9cdd54c528cbd63a3b148" ON "approval_requests" ("type", "target_id") `);
        await queryRunner.query(`CREATE TYPE "public"."ai_feature_enum" AS ENUM('chatbot', 'moderation', 'match_suggestion')`);
        await queryRunner.query(`CREATE TABLE "ai_usage_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "feature" "public"."ai_feature_enum" NOT NULL, "tokens_used" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7f42670987a1de5cb209a77e925" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5ae130ec36e163aca178827e5b" ON "ai_usage_logs" ("user_id", "feature", "created_at") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_5ae130ec36e163aca178827e5b"`);
        await queryRunner.query(`DROP TABLE "ai_usage_logs"`);
        await queryRunner.query(`DROP TYPE "public"."ai_feature_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_802fa9cdd54c528cbd63a3b148"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bcfff2aed6c93f6fa089720b3"`);
        await queryRunner.query(`DROP TABLE "approval_requests"`);
        await queryRunner.query(`DROP TYPE "public"."approval_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."approval_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f57a0c3adbbfd460935b7b046"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "user_rating_summary"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88452e999eb3af6a696a21dafe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4397e1893c028b96e04f208f76"`);
        await queryRunner.query(`DROP TABLE "field_rating_summary"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a15dfcd7aa8b8f61431364d19"`);
        await queryRunner.query(`DROP TABLE "user_reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0401bfc63155e3d2e154631c85"`);
        await queryRunner.query(`DROP TABLE "field_reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ca327ebb6c902e8bad5932105"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e64933661819e67db6986232c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9acc6efa76de013e8c1553ed2"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39a0b4bd3117b9d4c9cd696fee"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_status_enum"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8584a1974e1ca95f4861d975ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22133395bd13b970ccd0c34ab2"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."message_type_enum"`);
        await queryRunner.query(`DROP TABLE "conversation_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d863718b78a19a4259f34dcae2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19bb13367263f4abb451b75838"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TYPE "public"."conversation_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_427e1e52f6accefda55ac33020"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_547a10a97b30830634e4917ee8"`);
        await queryRunner.query(`DROP TABLE "post_matches"`);
        await queryRunner.query(`DROP TYPE "public"."match_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8eb985b7bd35fd7bc760b6cbe8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8ffd07822f03f90f637b13cd5"`);
        await queryRunner.query(`DROP TABLE "post_comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d6a751a1943909d10bcc5a140"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7374a48c04249418e45384b643"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4f9a7bd77b489e711277ee598"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TYPE "public"."post_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."post_skill_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_813fb23d7e327b6d9cff929cce"`);
        await queryRunner.query(`DROP TABLE "booking_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b406d71d65b8e16c5cf6e9b3ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88c0e04c7c95a23d0049ba05fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f80ee3c0f6b2adf57520dc9e97"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64cd97487c5c42806458ab5520"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."booking_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3766133563eefed9888347effa"`);
        await queryRunner.query(`DROP TABLE "field_pricing"`);
        await queryRunner.query(`DROP TYPE "public"."day_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb1beabceee095ac2e8ed72c25"`);
        await queryRunner.query(`DROP TABLE "field_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_756ccc25e9484dcf6453f90947"`);
        await queryRunner.query(`DROP TABLE "field_images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb774c35a4f3285bf483e801e5"`);
        await queryRunner.query(`DROP TABLE "field_courts"`);
        await queryRunner.query(`DROP TYPE "public"."court_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb540818c27426841e06b36b09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd7b6f73d3dbe8cb0cc5cd510c"`);
        await queryRunner.query(`DROP TABLE "fields"`);
        await queryRunner.query(`DROP TYPE "public"."deposit_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."field_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9da160266a21b0f39b6aeaca7"`);
        await queryRunner.query(`DROP TABLE "owner_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ca9503d77ae39b4b5a6cc3ba8"`);
        await queryRunner.query(`DROP TABLE "user_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."skill_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f169d18dc7fce81f4c20974fd0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
    }

}
